spring.application.name=user-service

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=wallet_user
spring.datasource.password=wallet_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info